<a href="https://colab.research.google.com/github/kenaceeee/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Final Exam

###Problem 1

In [12]:
import numpy as np
A = np.array([[1,1,1],[1,0,4],[0,0,5]])
B = np.array([[89],[89],[95]])
C = np.linalg.inv(A).dot(B)
print(C)

[[13.]
 [57.]
 [19.]]


###Problem 2

In [22]:
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
B = np.array([[5],[15],[-20]])
print(A)
print (B)
Ainv = np.linalg.pinv(A)
X = Ainv.dot(B)
print(X)


[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


###Problem 3

In [24]:
from numpy.linalg import eig
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)
w,v = np.linalg.eig(A) 
print("The eigenvalue/s are:",w.round())
print("The eigenvector/s are:\n",v.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvalue/s are: [-1.  3.  2.]
The eigenvector/s are:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
