<a href="https://colab.research.google.com/github/kenaceeee/Linear-Algebra-58019/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Using Python Codes, to find the inverse of a matrix, the matrix is passed to the linalg.inv() of the NumPy module

In [4]:
import numpy as np
A = np.array([[4,3],[-5,9]])
print(A)
inv_A = np.linalg.inv(A)
print(inv_A)

[[ 4  3]
 [-5  9]]
[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [6]:
B = np.array([[20],[26]])
print(B)

[[20]
 [26]]


In [7]:
X = np.linalg.inv(A).dot(B)
print(X)

[[2.]
 [4.]]


In [8]:
X = np.dot(inv_A,B)
print(X)

[[2.]
 [4.]]


###Application

In [14]:
A = np.array([[20,10],[17,22]])
print(A)
Inv_A = np.linalg.inv(A)
print(Inv_A)

[[20 10]
 [17 22]]
[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]


In [11]:
B = np.array([[350],[500]])
print(B)

[[350]
 [500]]


In [12]:
X = np.dot(Inv_A,B)
print(X)

[[10.]
 [15.]]


###To check if the answer is correct

In [13]:
B = np.dot(A,X)
print(B)

[[350.]
 [500.]]
