<a href="https://colab.research.google.com/github/kenaceeee/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Midterm Exam

###Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [28]:
A = (5,5)  
B = np.zeros(s)
print(B)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


###Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)



In [21]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
Zero = np.triu(A)
print(Zero)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


###Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)



In [31]:
A = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(A)


[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


###Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)



In [23]:
C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) #creation of matrix C
print(C)
inv_C = np.linalg.inv(C)
print(inv_C)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


###Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)



In [ ]:
C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])
det_C = np.linalg.det(C)
print(int(det_C))

5


###Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [ ]:
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
B = np.array([[[3.4],[8.8],[19.2]]])
print(A)
print(B)
roots = np.linalg.inv(A) @ B
print(roots)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]
[[[ 3.4]
  [ 8.8]
  [19.2]]]
[[[0.2]
  [0.4]
  [0.8]]]
