<a href="https://colab.research.google.com/github/kenaceeee/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Prelim Exam

###Question 1

In [4]:
#numpy
import numpy as np
C = np.full((4,4),1)
Diagonal = np.diagonal((C))
print("C =",C)
print("Diagonal = ",Diagonal)

C = [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Diagonal =  [1 1 1 1]


###Question 2

In [ ]:
import numpy as np
C = np.full((4,4),1)
print(C*C)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


###Question 3

In [ ]:
import numpy as np
A = np.array([2,7,4])
B = np.array([3,9,8])
output = np.cross(A,B)
print(output)

[20 -4 -3]


###Example

In [3]:
C = np.eye(4)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
