<a href="https://colab.research.google.com/github/kenaceeee/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Prelim Exam

###Question 1

In [ ]:
#numpy
import numpy as np
C = np.full((4,4),1)
Diagonal = np.diagonal((C))
print("C =",C)
print("Diagonal = ",Diagonal)

C = [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Diagonal =  [1 1 1 1]


###Question 2

In [7]:
import numpy as np
C = np.full((4,4),1) #to display the 4x4 matrix with the value of 1
print(C*2) #to print the 4x4 matrix doubled

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


###Question 3

In [6]:
import numpy as np
A = np.array([2,7,4]) #matrix A
B = np.array([3,9,8]) #matix B
output = np.cross(A,B) #cross multiply the martix A and matrix B
print(output) #to print the cross product

[20 -4 -3]


###Example

In [ ]:
C = np.eye(4)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
