<a href="https://colab.research.google.com/github/kenaceeee/Linear-Algebra/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

In [9]:
#numpy
import numpy as np    #sum = A + B
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A+B)

[[ 1 -3]
 [ 6  4]]


In [10]:
import numpy as np    #difference1 = B - A
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(B-A)

[[11 -3]
 [-2  2]]


In [11]:
import numpy as np    #difference2 = A - B
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A-B)

[[-11   3]
 [  2  -2]]
