<a href="https://colab.research.google.com/github/kenaceeee/Linear-Algebra-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vector Space Operations

## Representing Vectors

In [2]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


## Describing Vectors in Numpy

In [9]:
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
pool = np.array([ball1,ball2])
pool.shape
pool.ndim

2

In [15]:
U = np.array([[1,2,3],[4,5,6]])
U.shape

(2, 3)

In [22]:
U = np.array([[1,2,3],[4,5,6]])
U

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
U = np.array([[1,2,3],[4,5,6]])
U.ndim

2

In [17]:
U = np.array([[1,2,3],[4,5,6]])
U.size

6

## Spaces

### Vector Spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations

### Addition of Vectors

In [21]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
print(sum)

[1 1 0]


In [27]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.add(addend1,addend2)
print(resultant)

[1 1 0]


### Subtraction of Vectors

In [26]:
subtrahend1 = np.array([0,0,0])
subtrahend2 = np.array([1,1,0])
difference = subtrahend1 - subtrahend2
print(difference)

[-1 -1  0]


In [30]:
subtrahend1 = np.array([0,0,0])
subtrahend2 = np.array([1,1,0])
resultant = np.subtract(subtrahend1,subtrahend2)
print(difference)

[-1 -1  0]


### Scaling


In [32]:
A = np.array([1,5,8,9])
S = 5 * A
S

array([ 5, 25, 40, 45])

### Cross Product

In [33]:
A = np.array([2,3])
B = np.array([1,7])
output = np.cross(A,B)
print(output)

11


In [34]:
A = np.array([2,3,4])
B = np.array([1,7,1])
output = np.cross(A,B)
print(output)

[-25   2  11]


In [35]:
A = np.array([2,3])
B = np.array([1,7])
output = np.dot(A,B)
print(output)

23
