<a href="https://colab.research.google.com/github/kenaceeee/Linear-Algebra/blob/main/Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Algebra


In [2]:
#numpy 
import numpy as np
a = np.array([1,2,3]) #1x3 array
print(a)

[1 2 3]


In [5]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
import numpy as np
d = np.full((3,3),7)
print(d)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [12]:
import numpy as np
e = np.array([[1,2,3],[4,5,6],[7,8,9]])
f = np.diagonal([[1,2,3],[4,5,6,],[7,8,9]])
print(e)
print(f)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [15]:
import numpy as np
g = np.eye(3)
print(g)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
import numpy as np
h = np.zeros((2,2))
print(h)

[[0. 0.]
 [0. 0.]]


In [18]:
import numpy as np
i = np.empty((0,12))
print(i)

[]


In [19]:
import numpy as np
x = np.full((3,3),7)
print(d+d)

[[14 14 14]
 [14 14 14]
 [14 14 14]]


In [20]:
import numpy as np
y = np.full((3,3),7)
print(y-y)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
